export const RARE = {
	UNCOMMON: 'UNCOMMON',
	COMMON: 'COMMON',
	RARE: 'RARE',
	LEGENDARY: 'LEGENDARY',
	ARCANA: 'ARCANA',
}

export const RARE_WEIGHT = {
	[RARE.UNCOMMON]: 60,
	[RARE.COMMON]: 50,
	[RARE.RARE]: 25,
	[RARE.LEGENDARY]: 5,
	[RARE.ARCANA]: 3,
}
