name: Deploy Idle-D

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cd /home/idled
            git reset --hard
            git pull origin master

      - name: Backup current Nginx configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cp /etc/nginx/sites-available/idled.xploit.ltd /etc/nginx/sites-available/idled.xploit.ltd.backup

      - name: Update Nginx configuration
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cp /home/idled/idled.xploit.ltd.nginx /etc/nginx/sites-available/idled.xploit.ltd
            ln -sf /etc/nginx/sites-available/idled.xploit.ltd /etc/nginx/sites-enabled/idled.xploit.ltd

      - name: Test Nginx configuration
        id: nginx_test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            sudo nginx -t || (echo "Nginx configuration test failed" && exit 1)

      - name: Restore previous Nginx configuration if test fails
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cp /etc/nginx/sites-available/idled.xploit.ltd.backup /etc/nginx/sites-available/idled.xploit.ltd
            sudo nginx -t && sudo systemctl restart nginx

      - name: Restart Nginx
        if: success() && steps.nginx_test.outcome == 'success'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            sudo systemctl restart nginx

      - name: Create Docker build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cd /home/idled
            docker rmi -f $(docker images -q "xploitravy/idled")
            docker build . -t xploitravy/idled:latest

      - name: Restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SERVER_HOST }}
          username: ${{ secrets.VPS_SERVER_USERNAME }}
          key: ${{ secrets.VPS_SERVER_SSH_KEY }}
          script: |
            cd /home/idled
            docker-compose down
            docker-compose up -d

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1304151344726147163/D3xqlHDeDYBt2xgKeNrUn6qylgFmUn6QFg62s_gKe20XRJiVYK6oKKVWB4300NShkrg_
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"https://ravy.pro successfully updated! Commit: $LAST_COMMIT_MESSAGE\"}" \
            ${{ env.DISCORD_WEBHOOK_URL }}

