name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Generate build
        run: npm run build

      - name: Upload to FTP
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./dist
          remoteDir: /

      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1304151344726147163/D3xqlHDeDYBt2xgKeNrUn6qylgFmUn6QFg62s_gKe20XRJiVYK6oKKVWB4300NShkrg_
        run: |
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"https://idled.xploit.ltd game successfully updated! Commit: $LAST_COMMIT_MESSAGE\"}" \
            ${{ env.DISCORD_WEBHOOK_URL }}

